export const extractText = `INTRODUCTION
In the education of Ghanaian students, very little efforts are attached to community histories. Much of the interest are often directed towards the general socio-political narrative on the growth of the country than the individual communities and their unique stories that captures their contributions to the collective development of Ghana. Consequently, these distinct narratives that account for these communities are either limited to a few court members and individual or lost over time, in some cases. The focus of this writeup, therefore, is to trace the origins of Assin Manso, exploring aspects of the community's, socio-cultural and economic evolution to preserve it unique identity that has shaped the lives of its people, the legacy of the slave trade and its contribution to the global narrative of Africans, informing the need to acknowledge and appreciate it. 

The central region is home to a varied number of people with different ethnic affiliation, although predominantly Akan, with a considerable Etsi (Guan) population, "who were displaced with the arrival of the Fante's, according to Gocking". Amongst these community are the ones created by the Assin people. "There are generally two subdivisions of the Assin people, which includes Assin Apemenim living to the east of Cape Coast-Kumasi highway, with Manso as the capital and is also the primary focus of this writeup, while the Assin Attandanso lived to the west of the highway, with Nyankumasi as their capital.  The Assin have settlements such as Assin Foso, Assin Nyankumasi, Assin Akonfudi, Assin Bereku, Assin Praso, Assin Kushea amongst others". 

The Assin name also known as Asin or Asen, according to all oral accounts was acquired from the description of the procession as they moved from Asante to their present home. The unusually large number of the people during the exodus required that they announce their presence as the procession advanced. "The Akan phrase 'yℇ sen' which means 'we are passing' became the favoured chant. It was this phrase that over time was altered into 'Assin', which means 'Have passed'". 

To add to the historical importance and identity of Manso, is the famous landmark "Assin Manso Slave site". "The site, which later became the spot where captured slaves from various parts of the continent were marched in shackles to for their last bath (in the slave river also known as Ndonko Nsu) before they were sent to the various castles at the coast which were originally a designated lodgings for court attendants or slaves, while they awaited the summons from the king." However, the high commercial value of the slave trade informed the making of the place a slave market. "At the market slave were sorted, purchased and branded by the European companies", Thereafter, they continued their rather difficult journey to the Americas. "The community was also the intermediate depot for the British troops during the Yaa Asantewaa war".

Origin 
Contrary to John A. Nyarko who argued that the Assin people migrated from the north of Africa where they crossed Kemet, settling in Southern Sudan (Nubia) around 500 AD and later moved west establishing small kingdoms around 750 AD- 1200 AD. Oral history of the people suggests that the Assin people were created here and were originally a part of the Asante imperial hegemony, with Ansa (which is a community located in the Adansi North district of the Ashanti region of Ghana) as their original home. Assin people were described as trained warriors, belonging to the Asante heritage, who played the role of vanguards to the empire in times of war, and were instrumental to the rise and expansion of the Asante Empire. 

There are varying opinions on why or how the people had to migrate to their present settlement. One asserts that the great trek by the people became necessary because of fear of retribution from the Asantehene. According to this account, "the leaders of the Ansa faction of the Asante's were charged to collect rents from conquered subjects of the empire. However, upon collection of the rent, the Ansa leadership refused to return the said rent to the Asante treasury. Fearing the wrath and the extent of Asante's vengeance, the two later Assin faction (Apemenim and Attandanso) left their settlement in the empire, first settling at Dansameng, presently around Asempa na eye. In their new settlement, the warrior groups became as explained, army for hire, "aiding the highest bidder in various military campaigns. This state of affairs saw them moving from one place to the other to render their services". The next destination after Dansameng was Assin Bereku, where a section of the group was left off as the larger stock continued the journey, finally arriving at their present settlement, settling around a rubber plantation".

Another oral history asserts that the people of Manso were warriors who were invited by the Guan population of Andoe in the central region. The two Assin factions were then believed to have been charged with the mission of assisting the Andoe people to halt the Dutch growing influence in the region, which seemed to have been informed by economic interest. These events, most likely took place during the reign of Asantehene Nana Kusi Oboadum, who was king of the empire in 1752 and was renowned for his various ploys to spread the influence of Asante to the coast. Although there is very little available literature to support this clash with the Dutch and its outcome. It is however implied that the campaign was successful and the combined military force of Andoe and Assin toppled the European expansion to the area, driving the Dutch forces as far back to Abura Asebu, who at the time, shared boundaries with Andoe. 

Following this victory, the Assin duo retreated to Bereku where they stayed for a while, until the Apemenim wing, who were led on their jouney by Nana Kofi Mintah was given the stretch of land they occupy currently. As both Nana Aboagye and Mr. Addo narrated, the creators of Assin Manso, favoured settling around a 'rubber tree' which in the Akan parlance (Fante to be more precise) is "Aman Dua", from which the name Manso was acquired. 

Development
The growth of Manso from the community's inception can largely be attributed to the economic value it possessed. "Being a nodal town, Manso gradually became an important trade centre where trade items from the interior were brought to for sale to various merchant parties, including Europeans". The general chaotic atmosphere in the region at the time, occasioned by the high demand for slave's labour in the Americas also meant an increase in raids, kidnappings and wars to accommodate this need. This implied that European merchants had to confined their economic interests to specific places to be safe, such as Manso. Hence Manso grew in prominence and popularity, and this attracted people from different places to Manso. It is however noteworthy to establish that the natives of Manso have predominantly been farmers, "cultivating a wide variety of crops such as plantain, cassava, vegetables among other". 

Social Organisation
As a consequence of the strong allegiance to the Asante Empire, the socio-cultural and traditional landscape of Manso is reflective of their affiliation to the Akan ethnic group. Politically, Assin Manso have maintained a powerful status in the Apimenem traditional area as its paramountcy. The unified and peaceful environment in the community is a testament of the strong and able leadership qualities of the kings of Manso who are usually selected from the Asona clan. 

Assin Manso, which is a matrilineal subscribing is also culturally known for their vibrant traditions and institutions, including marriage rites, funeral rites and festivals such as Tutu Afahye and slave emancipation festivals, which is an international festival and the various traditions designed to honour their ancestor and gods who are mostly river gods.`;
